### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ShevchenkoRostyslav**
Update for 2015/2016 functionality.
if everything will work fine - can you merge and create a new branch for 2015 tag? Then Chayanit and I will modify it and we will freeze 2015 analysis.

### CODE REVIEW

**Comment by robervalwalsh** [comment]
@ShevchenkoRostyslav Are these modifications also to be used with 2016 analysis? If so I can merge with the main branch in addition to create another branch for 2015 analysis only.

**Comment by ShevchenkoRostyslav** [comment]
Exactly. This modification should be applied in general and then 2015 branch can be produced. Thanks.

**Comment by robervalwalsh** [comment]
Great! Then procedure is more straightforward. Thanks!

**Comment by robervalwalsh** [comment]
The PR was merged with the develop branch. Another branch called [analysis-2015](https://github.com/desy-cms/analysis/tree/analysis-2015) has been created from the develop branch without the package Diagnosis because it is not compatible wth CMSSW_7_6_X.

The tag [analysis-2015-v1](https://github.com/desy-cms/analysis/tree/analysis-2015-v1) was also created as a frozen version of the branch analysis-2015 as of today.

All modifications for the 2015 analysis has to be done in the branch analysis-2015 and requested to be pulled to that branch, not to the branch develop!  In case of common modifications, one should make two PRs, one for each branch.

**Comment by ShevchenkoRostyslav** [comment]
Thanks a lot for your work! 

best regards,
Rostyslav

———————————————————————————
Rostyslav Shevchenko | EMail: shevchenko.rostislav@gmail.com
DESY                 | Mail: DESY, CMS, Notkestr. 85, D-22603 Hamburg, 01b. 02-215
                     | Phone: +49 40/8998-5673
———————————————————————————

**Pull request merged**
